name: schedule

on:
  schedule:
    - cron:  '*/10 * * * *'


jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: wei/curl@master
        with:
          args: ${{ secrets.DEPLOY_HOOK_URL }}